config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :countries
    resources :addresses

    resources :states

 get 'addresses/get_states/:id', to:'addresses#get_states'
  root 'addresses#index'

end

app/models/state.rb
class State
  include Mongoid::Document

  field :name, type: String
  field :is_Active, type: Boolean

  has_many :addresses
  belongs_to :country

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @countries = Country.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @country_id = @state.country_id
    @country = Country.find(@country_id)
  end

  # GET /states/new
  def new
    @country = Country.all
    @state = State.new
  end

  # GET /states/1/edit
  def edit
    @country = Country.all
  end

  # POST /states
  # POST /states.json
  def create

     @country = Country.find(params[:country_id])
    @state = @country.states.create(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:country,:name,:is_Active)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>Country     <select name="country_id">
      <%= @country.each do |country| %>
          <option value="<%= country.id %>"><%= country.name %></option>
      <% end %>
    </select></p>
    <p>State Name <%= f.text_field :name %></p>
    <p> <%= f.check_box :is_Active %>Active</p>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <thead>
    <tr>
      <th>State Names</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @countries.each do |c| %>
  <% c.states.each do |s| %>
      <tr>
        <td><%= s.name %></td>
        <td><%= link_to 'Show Details', s %></td>
        <td><%= link_to 'Edit state', edit_state_path(s) %></td>
        <td><%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New State', new_state_path %><br>
<%= link_to 'Manage Countries ',controller: countries_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<div>
  <p>Country: <%= @country.name  %></p>
  <p>State: <%= @state.name  %></p>
  <p>Active: <% if @state.is_Active -%>
             <%= "yes"  %>
        <% else %>
        <%= "No"  %>
              <%   end     %></p>
</div>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>