config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :countries
    resources :addresses

    resources :states

 get 'addresses/get_states/:id', to:'addresses#get_states'
  root 'addresses#index'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /addresses
  # GET /addresses.json
  def index
    @user = User.find(current_user.id.to_s)
    @addresses = @user.addresses
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @state_id = @address.state_id
    @state = State.find(@state_id)
    @country_id = @state.country_id
    @country = Country.find(@country_id)
  end

  # GET /addresses/new
  def new
    @address = Address.new
    @country = Country.where(is_Active: true)
  end

  # GET /addresses/1/edit
  def edit
    @country = Country.where(is_Active: true)
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @user = User.find(current_user.id)
    @state = State.find(params[:name])
    @address = @state.addresses.create(address_params)
    @user.addresses << @address
    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def get_states
    @country = Country.find(params[:id])
    @state = @country.states.where(is_Active: true)
  render json: @state
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:firstName,:lastName,:email,:phoneNo,:address1, :address2,:street,:city,:zipCode)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>First Name <%= f.text_field :firstName %></p>
    <p>Last Name    <%= f.text_field :lastName %></p>
    <p>Phone No    <%= f.text_field :phoneNo %></p>
    <p>Country     <select id = 'select_id' name="country_id">
      <option value=""></option>
      <%= @country.each do | country | %>
          <option value="<%= @id = country.id %>"><%= country.name %></option>
      <% end %>

    </select></p>

    <p>State    <select id ='state'  name="name" >
                    </select></p>
    <p>Address1<%= f.text_field :address1 %></p>
    <p>Address2<%= f.text_field :address2 %></p>
    <p>Street<%= f.text_field :street %></p>
    <p>City<%= f.text_field  :city %></p>
    <p>Zip Code<%= f.text_field  :zipCode %></p>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type = 'text/javascript'>
    $(document).ready(function(){

        $("#select_id").change(function(){

            if ($(this).val() == '')
            {
                $('#state').html( $('<option> No state provided </option>'));
            }
            else {
                $.ajax({
                    type: "GET",
                    url: "/addresses/get_states/" + $(this).val()+'',
                    success: function(data){
                        $('#state').empty()
                        i=0;
                            $.each(data, function(key, value) {
                            $('#state')
                                    .append($("<option></option>")
                                            .attr("value",data[i]._id.$oid)
                                            .text(value.name));
                            i++;
                        });

                    }

                });
            }
        });
    });

</script>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <thead>
    <tr>
      <th>firstName</th>
      <th>lastName</th>
      <th>phoneNo </th>
      <th>Details</th>
      <th>Edit Details</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <% @state_id = address.state_id %>
      <% @state = State.find(@state_id.to_s) %>
      <% @country_id = @state.country_id %>
      <% @country = Country.find(@country_id.to_s) %>
      <tr>
        <td><%= address.firstName %></td>
        <td><%= address.lastName %></td>
        <td><%= address.phoneNo %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Add New Address', new_address_path %>
<br><br>
<div>
  <%= link_to 'Manage Countries ',controller: countries_path %>
  <%= link_to 'Manage States ',controller: states_path %>
</div>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>


<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<div>
  <p>First Name:      <%= @address.firstName %></p>
  <p>Last Name:       <%= @address.lastName %></p>
  <p>Email:           <%= @address.email %></p>
  <p>Contact No:      <%= @address.phoneNo %></p>
  <p>Country:          <%= @country.name %></p>
  <p>State:            <%= @state.name %></p>
  <p>City:             <%= @address.city %></p>
  <p>Address:          <%= @address.address1+@address.address2 %></p>
  <p>Street:            <%= @address.street %></p>
  <p>Zip Code:          <%= @address.zipCode %></p>

</div>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>