config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :countries
    resources :addresses

    resources :states

 get 'addresses/get_states/:id', to:'addresses#get_states'
  root 'addresses#index'

end

app/models/country.rb
class Country
  include Mongoid::Document

  field :name, type: String
  field :is_Active, type: Boolean

  has_many :states, dependent: :destroy,:autosave => true

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
      @states = @country.states
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name,:is_Active)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>Country Name <%= f.text_field :name %></p>
    <p> <%= f.check_box :is_Active %> Active</p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Country Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Country', new_country_path %><br>
<%= link_to 'Manage States ',controller: states_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<div><p>Country:<%= @country.name %></p>
  <p>Active: <% if @country.is_Active -%>
        <%= "yes"  %>
    <% else %>
        <%= "No"  %>
    <%   end     %></p>
  <%= link_to 'Edit', edit_country_path(@country) %> |
  <%= link_to 'Back', countries_path %><br><br><br>


  <table><tr><th>States</th></tr>
    <tr><td><% @states.each do |c| %>
          <%= c.name%><br>
    <% end %></table>
  </th></tr>
</div><br>